### PR TITLE
[RFC] applying pyupgrade to the code

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
pyupgrade is a automated code-formatter that automatically updates code patterns it recognizes as superseded with more modern versions

for example format strings, implied object as base class, yield loops and more

i love its assistance, but i understand hesitation against it,
it was trivial to create this pr, i hope it finds resonance,
but i'm fine if it doesn't

if there is resonance for the tool, i'd also like t know if there is any interest in having tools like pre-commit and black assist the development in future (i'm fluent with those and happy to add them id they are liked/well-received)

### CODE REVIEW

**Comment by pfalcon** [comment]
-1 for this tools

+1 for switching to PEP8-compatible 4-space indents, and stop there.

But given that the codebase is not PEP8 compliant for ages, and even useful PRs are not getting merged, I guess no changes will be applied at all ;-). (And useless changes like reformatting definitely should be applied only after dealing with useful functionality-related PRs backlog.)

**Comment by jaap-karssenberg** [comment]
@RonnyPfannschmidt  I actually do agree, a tool like this can improve the code quality and readability up to "modern" python standards. However, in my experience it is always hard to do these actions without breaking work in progress. Given that I'm working on multiple branches with significant change sets compared to master, I'm afraid the integration after applying such update will be a hassle. Will keep it on the backlog for a moment in time I have less work in parallel.

@pfalcon  no, I'm not going with spaces instead of tabs - I'm quite stubborn about that one ;)

**Comment by RonnyPfannschmidt** [comment]
@jaap-karssenberg this thing can be easily redone on top of a more recent master after larger changes

is there  anything that can be done to help you with the larger changes?

the insistence on tabs is a massive pain factor for me personally ^^

**Comment by RonnyPfannschmidt** [comment]
closing as deferred indefinitely

**Pull request closed without merging**
