### PR TITLE
Plugin for detecting and merging changes on disk

### PR DESCRIPTION
**Pull request by joukhaha**
Hello,
this intends to provide the functionality of an earlier pull request #178 in the form of a plugin that can be enabled and controlled through plugin settings.
Needs testing, but overall the current implementation is much simpler than previously, to the point where it might more comfortable that this gets the job done in a more reasonable way that aligns better with zim's code. Feel free to comment and provide pointers if this is not the case...

If the users of the earlier modifications are willing to give it a test and comment (I will do more tests later as well), it should be possible to iron out possible issues. According to zim manuals, the installation of the plugin should also be possible simply by copying the plugin directory (zim/plugins/diskmerger) into zim plugin directory (but didn't try this yet). If @jaap-karssenberg considers better to keep this as a custom plugin living outside zim, that should also be a possibility.

One feature of the plugin now is that if it's configured to compare the changes on disk and buffer, it will always report differences in the header. This seems to appear because zim for some reason parses the header on disk and on buffer differently in array elements. Ideally this might be fixed in zim. A major improvement with respect to the older version is also that this one should not screw up tables (as easily implemented by adapting some functions that were already built in).

### CODE REVIEW

**Comment by dehesselle** [comment]
Can you change this to target the `develop` branch? The project has moved to the strategy of "master is production" and all development needs to happen in `develop`. Apologies for the inconvenience.

**Comment by joukhaha** [comment]
Certainly, if/when I find straightforward means to do that... But based on a quick check it would appear that it would be easiest on the upstream repo (in the pull requests there should be a direct button to change base branch):
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request.
Or is there a better way?

**Comment by introt** [comment]
If the drop-down isn't appearing for you after clicking "Edit", it'd probably be easiest if you'd close this PR and open a new one. Us underlings can't do that for others' PRs, sorry!

**Comment by jaap-karssenberg** [comment]
Sounds like great functionality to have, but really need to have good test
coverage in the test suite before we can merge it. Could you add test cases
for this plugin ?

**Comment by joukhaha** [comment]
(I assume the plugin succesfully transferred to development branch now.. sorry for the late notice and thanks for the tip, Dehesselle).

Figuring out how to add test coverage for the plugin is not really something that is obvious to me, unfortunately. In principle I would not mind trying to learn more about it, but can't say if/when I might have time for it. Some suggestions and pointers on how to approach the testing problem would, however, be quite useful if I get to that point...

**Comment by introt** [comment]
> Figuring out how to add test coverage for the plugin is not really something that is obvious to me, unfortunately. In principle I would not mind trying to learn more about it, but can't say if/when I might have time for it. Some suggestions and pointers on how to approach the testing problem would, however, be quite useful if I get to that point...

https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1376 can be used for reference:

> Ideally we should also have a specific test case for the plugin itself. Just run the dialog in a test and check it runs without errors would be a good start

Here's the corresponding code: https://github.com/datenwurm/zim-desktop-wiki/blob/c0874ccc4dd4ed5e854be05ffc36b05c7e40adbc/tests/command_palette.py#L4-L14 (~10 lines)

**Comment by kanehekili** [comment]
I've been using Tomboy for almost 15 years, and it simply copied an "old" version and marked it so. I did not expect a "modern" application of not being able to handle working on different devices. (which implies merge conflicts)

**Comment by joukhaha** [comment]
Ok, long time without anything happening, but now I added the simple test case used as an example above. Running test.py diskmerger seems to pass (no errors, at least). I also made some fixes/hacks to dealing with file permissions, as they seemed to be non-functional if different users edited the files. Largely stuff should still be considered untested, though. I guess I'll need to remake the pull request somehow to keep this on the list of possible future additions....

**Comment by kanehekili** [comment]
My use case: I am a single user with more than one device. On each device  your software is installed. They "sync" with a cloud instance. My expectation: "Push" a note from device A. Later  "pull" from device B. If device B has changed that note as well I 'd expect a "merge conflict" by having two versions of the same note. Tomboy solves that with a new note that is called "xxx.old". So it's not a multi user problem, rather a multi device problem (..from my point of view). By (software) design it should make no difference if two users or two devices produce that situation.

**Pull request closed without merging**
