### PR TITLE
Feature: Bujo backarrow

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this adds a bullet journal back arrow to complements the already existing arrow for documenting the normal migration

the bullet journal method has 2 types of migration

* `>` migration which documents the move of a task not completed in the current day/log to a new day/log
* `<` migration, which documents the move of a task to a future collection for further refinement

as  it affects both text syntax and integrated actions i saw no way of implementing this in a plugin

its possible to go on with just documenting everything as "normal migration" but that takes away information useful for reflection

TODO:
- [x] check wiki format version bump
- [x] mini intro for bujo
- [x] squash

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
the feature now roughly works

**Comment by pfalcon** [comment]
What is bujo backarrow? Why do we need bujo backarrow? How did we manage to survive without bujo backarrow for so long?

See https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/CONTRIBUTING.md#adding-new-features for inspiration.

**Comment by RonnyPfannschmidt** [comment]
the bullet journal back arrow complements the already existing arrow for documenting the normal migration

the bullet journa method has 2 types of migration

* `>` migration which documents the move of a task not completed in the current day/log to a new day/log
* `<` migration, which documents the move of a task to a future collection for further refinement

as  it affects both text syntax and integrated actions i saw no way of implementing this in a plugin

its possible to go on with just documenting everything as "normal migration" but that takes away information useful for reflection

**Comment by pfalcon** [comment]
Counter-argument to that is that even existing Zim "extensions" pose interoperability issues with other (more popular, up to being a de-facto standard) markup formats (e.g. https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/26#issuecomment-708189950).

**Comment by RonnyPfannschmidt** [comment]
if interoperable means that everyone can do next to nothing, that seems to be a flaw
there always is a friction between common feature sets and distinctive features.

As the  de-facto standards are not extensible, this is a problem.

even for restructured text only a crude hack comes to mind to add this feature in a pristine way.

**Comment by pfalcon** [comment]
I fully agree that "if Zim already went beyond simple on/off checkboxes, then it as well can be extended further" is a good argument, I just point out it's *not the only* argument ("stop any adhoc additions" is also a pretty good one).

The biggest point though is that proposed changes should be well described (and even justified). As of now, the description here is still:

> this intends to add bujo style back arrows to checkboxes

Hopefully, that will be fixed eventually.

**Comment by jaap-karssenberg** [comment]
Patch looks good to me and I intend to merge it. Could you also add some content to the manual (data/manual in the source folder) explaining this checkbox type? Maybe even a short intro to bullet journaling in the "usage" section. Also would like to see a test case that uses this checkbox type to make sure it does not break later.

With respect to the above discussion. Since I already added "`[>]`" I see no good argument to block "`[<]`". Yes, this poses an issue when we go to MarkDown, but merging now in our wiki format still leaves open the choice what we support for MarkDown and how we do that. So not a blocking issue right now.

Regards,

Jaap

**Comment by RonnyPfannschmidt** [comment]
should there be a bump of the wiki format version number (so old zim does not stumble?

**Comment by jaap-karssenberg** [comment]
Only if you also patch the parser to parse without this bullet support when
the version of the page is lower. And patch the dumper to somehow escape
the sequence on write. Since there is no escaping format in zim right now
this is difficult.

Risk is low in my opinion - not much use for a " [<] " sequence in regular
use I suspect - so I'm OK without version bump.

-- Jaap

**Comment by RonnyPfannschmidt** [comment]
@jaap-karssenberg do you by chance  know a example of the escaping mechanism - i'd like to attempt the version bump if i can  figure a sensible iteration sometime this month, else i'll defer to the non-bump version (which is also fine, just irks me if i haven't at least tried the bump)

**Comment by jaap-karssenberg** [comment]
Afraid adding an escape requires refactoring of the parser. Have that on my
long term plan but moving slow.

Op ma 11 jan. 2021 00:24 schreef Ronny Pfannschmidt <
notifications@github.com>:

**Comment by RonnyPfannschmidt** [comment]
I see, in that case a escape is not a sustainable way to do it right now,

If you agree that the risk is acceptable, I'd like to implement it without version bump then

**Comment by jaap-karssenberg** [comment]
Yes, as stated: risk is low in my opinion - not much use for a " [<] "
sequence in regular use I suspect - so I'm OK without version bump.

**Comment by RonnyPfannschmidt** [comment]
@jaap-karssenberg gentle ping on this one, 
i forgot to mention that i ended the experiment,
i'd appreciate if this was part of one of the next releases

**Comment by jaap-karssenberg** [comment]
Yes it is on my list, but progress is very slow on integrating as the whole
lockdown put a big strain on my available time

**Comment by introt** [comment]
The backarrow is missing from the `Edit > Checkbox` menu for some reason, though the `@action` code exists (and works- I confirmed this by swapping the names of the functions). The following functions mention migrated_box, but not the transmigrated variant:

- `do_mark_set` (adding a line here didn't make the action show up)
- `get_bullet` (docstring)
- `toggle_checkbox` (docstring)
- `set_bullet` (docstring & comment)

Also, is the backarrow supposed to appear before the forward variant in the popup menu (populated in reverse order by `_checkbox_do_populate_popup)`?

While investigating I noticed the backarrow's absence from some export formats & their tests; I hopefully #1473 should take care of those.

Thanks for adding the backarrow, I've found it repeatedly useful for task planning!

**Comment by RonnyPfannschmidt** [comment]
@introt thanks for iterating on the details, i wasn't aware how many detail locations i missed, i wonder of this can be condensed/dry-ed out as a follow-up

**Comment by introt** [comment]
No problem! Took me a while to find them all, in the end I just grepped for the MIGRATED_BOX and worked the missing pieces out from there... I don't know what's the best way for Jaap. Some of your commits have already made it into the `develop` branch which I based by PR on while this PR is based on the `master` branch so a simple rebase may not be conflict-free. I really should have thought this through better!

Let me know if you want me to try rebasing & sending a PR to your branch so that it'll get included in this PR.

**Comment by jaap-karssenberg** [comment]
@RonnyPfannschmidt do you want to check and merge the fixes by @introt - or shall I have a go at merging both pulls ?

**Comment by RonnyPfannschmidt** [comment]
Thanks for the ping, I missed the pr on my fork, will give it a try in about 10

**Comment by RonnyPfannschmidt** [comment]
@jaap-karssenberg th merge went well, i'll now take a look at running the tests again

**Comment by jaap-karssenberg** [comment]
Thanks !  Now fully merged this tree into develop. In case of further updates, please commit a fresh pull request on a new branch.

**Pull request closed without merging**
