### PR TITLE
Matplotlib plugin

### PR DESCRIPTION
**Pull request by scholi**
Hi Jaap,
We spoke last year per email about a matplotlib plugin.
If you still have interest, I have created a pull request so that others can also use it.
The Manual is minimalistic, but it should be easy to understand how it works for people using matplotlib.

Let me know if you have comments/wishes about how to improve this plugin.

Kind regards

Olivier

### CODE REVIEW

**Comment by jaap-karssenberg** [comment]
Needs update to latest version - interface for image generator plugins has changed

**Comment by scholi** [comment]
Hi Jaap,
Sorry I forgot about it. I'll try to do it soon.

Kind regards

**Comment by pfalcon** [comment]
This isn't a "matplotlib plugin", but "arbitrary code execution plugin". While definitely nice and cool, it should be marketed as such.

**Comment by jaap-karssenberg** [comment]
Unfortunately this pull request cannot be merged as is. Without further activity or new insight it will be closed in a couple of months.

**Comment by jaap-karssenberg** [comment]
See #1610 for background on cleanup.

**Pull request closed without merging**
