### PR TITLE
Daily due dates in weekly journal

### PR DESCRIPTION
**Pull request by nelas**
Dear Jaap,

This is the pull request based on #443 (and [this thread](https://lists.launchpad.net/zim-wiki/msg04589.html)) to extract daily due dates from the weekly journal page (default template).

zim-daily-weekly

**Setup:**
- Properties > Journal > Use a page for each: > Week
- Properties > Task List >Use date from journal pages: > as due date for tasks

**What I did:**
1. Get header text from `head` in [_parse_heading()](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L357).
2. Use `datetime.strptime` to [parse the date](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L365) from the header (e.g. "Monday 14 May"). This is done in a separate function [_parse_heading_due_date()](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L373).
3. Modify `_parse_heading()` to also return the [parsed date](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L369).
4. Update the due date of the object [defaults](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L333), making all subsequent tasks have the new date (until the next header).

**Potential issues:**
- I imported the [default datetime](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L10) to use `strptime`. It's probably better to define `strptime` in `zim.datetimetz`.
- The headers have no year, so `strptime` sets it to 1900. To fix, I replace it by the [default_due_date.year](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L331).
- Modifying `_parse_heading()` to [return multiple values](https://github.com/nelas/zim-desktop-wiki/blob/a61f01c5161aa97f5888a2942097abee7b7f7afe/zim/plugins/tasklist/indexer.py#L326) might break something (tests went ok, though). But perhaps there is a better way.

Best,
Bruno

### CODE REVIEW

**Comment by jaap-karssenberg** [comment]
I like the idea, but would want to make the parsing of the heading a bit more robust.

Since you already know the week, the heading only needs to give the day, so instead of strptime you might as well just use a regex to match a number. Probably more robust for locale settings etc.

**Comment by nelas** [comment]
Hi Jaap, thanks for the feedback. I've altered the code to get the day using regular expression. It works, but there is a problem when there is a month transition like the one below.

Since the default due date here is `April 04`, when it fetches the `Tuesday 31 March`, it assigns it to `April 31`, which doesn't exist: `ValueError: day is out of range for month`. In addition, the wrong dates are assigned to the earlier dates March 29th and 30th (assigned to April).

Without `strptime`, there must be a way to identify the heading month. Any ideas?

```
Week 14 2020
============
29 March to 04 April

#### Sunday 29 March
[ ] Wrong due date

#### Monday 30 March
[ ] Wrong due date

#### Tuesday 31 March
[ ] Due date fails

#### Wednesday 01 April
[ ] Due date ok

#### Thursday 02 April
[ ] Due date ok

#### Friday 03 April
[ ] Due date ok

#### Saturday 04 April
[ ] Due date ok
```

Cheers,
Bruno

**Comment by jaap-karssenberg** [comment]
The "daterange_from_path" gives both a start and an end date. Now we pass
along only one of these, but if we add the range as context in the parse we
can match the day numbers to dates in the range by looping through them.

That way you only need a number in this range to match to the right date.

To clarify: my objection to strptime is that you now need to match the
search pattern to the template. If you go that route, you somehow need to
pull this information from the template into the page and then into the
parser. Else the function breaks as soon as someone changes the template
(like I do fo my personal notebook ;)  )

Regards,

Jaap

**Comment by nelas** [comment]
Ok, I think I got it working! I've added a `daterange` option to the `TaskParser.parse` method, and used that to loop and find the heading's date. It then sets the heading date as start or due date, depending on the values in the `defaults` list. Let me know what you think. Cheers

**Comment by jaap-karssenberg** [comment]
Sorry, but it looks like you pulled a lot of other commits into your branch
- impossible to review the changes now.

Can you rebase your changes such that the merge request only show your
changes? (Or open a new request with a clean branch if that is easier.)

Thanks,

Jaap

**Comment by nelas** [comment]
Hhm, ok. Just force-pushed a rebase but it's still messed up. I probably pulled the develop branch over this on the previous push... I'll open a clean branch.

**Comment by nelas** [comment]
Alright! I managed to clean it up and put it in one commit.

**Comment by jaap-karssenberg** [comment]
Would like to add
- test cases, specific where week covers boundary between months
- extend regex to also match fully specified dates yyyy-mm-dd or wyyww.d

**Comment by jaap-karssenberg** [comment]
My apologies for leaving this pull request hanging for over a year. Started merging it with a branch that contains more tasklist improvements and realized I still don't feel comfortable with the parsing of the headers - it feels fragile e.g. in case there are numbers in the heading for another reason.

However, I also came up with the solution. Will also merge the pull request that introduces "anchors" #1293 . This allows inserting identifiers in the page that can be used for linking etc. So my best idea is to modify the journal template to have unambigous identifiers for the headings - e.g. #20210412 for today - and thus allowing to link directly to a date in a week or month page, but also allowing to parse the heading and find the correct date for the heading without any special intelligence.

Will keep this patch as you submitted it, but rework the parsing to use anchors instead of a number in the heading text.

**Comment by nelas** [comment]
Hi Jaap, no problem. I also think the parsing is fragile. Using the anchor identifiers is a good solution!

**Pull request closed without merging**
