### PR TITLE
Fix crash in Edit Image dialog when the image file does not exist

### PR DESCRIPTION
**Pull request by qtonthat**
When the image file does not exist, Edit Image dialog failed to come up.
It was caused by ZeroDivisionError exception (shown by zim -V).

This simple change will the problem.

### CODE REVIEW

**Comment by qtonthat** [comment]
Missing image files can be common problems when users move sections between pages. I would suggest to offer users a chance to easily correct the problem using a dialog (as my commit does) rather than just raise exception and force them to edit the source text directly. It seems natural for users, seeing a broken icon in a page, to pop up the dialog to fix it.

**Comment by jaap-karssenberg** [comment]
Sorry, from your patch that behavior was not obvious, because the other
path this may occur (the except block) was unchanged.

-- Jaap

**Comment by qtonthat** [comment]
> Sorry, from your patch that behavior was not obvious, because the other path this may occur (the except block) was unchanged.

You're right.

**Comment by jaap-karssenberg** [comment]
Looking at this again it seems with my patch you can still edit images that do not exist. Can you clarify the issue you see with the patch?

**Comment by qtonthat** [comment]
Your patch was fine. It was my thinking that wasn't.

**Pull request closed without merging**
