### PR TITLE
New Windows deployment

### PR DESCRIPTION
**Pull request by fmos**
This is a new build script using PyInstaller. As PyInstaller does not support cross-compilation, the build script must be run on MSys. The script includes the Qogir-light Gtk 3 theme. Steps to build the installer are documented in windows/README.md.

### CODE REVIEW

**Comment by fmos** [comment]
Missing PyInstaller spec-file. see #639 Will fix and reopen asap.

**Comment by fmos** [comment]
Fixed spec file and icons.

**Comment by fmos** [comment]
OK, I have tested and finalized this version. Should be ready to merge.

**Comment by fmos** [comment]
The Gtk theme the build script was previously including has a greyish font color. This degrades readability. The default theme is perfectly fine from a functional view. If anyone prefers a different theme, they can probably override this via custom settings.

**Comment by jaap-karssenberg** [comment]
Merged in "develop" branch and published installer on https://zim-wiki.org/downloads/

**Pull request closed without merging**
