### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ahangarha**
Simple conversion of README.txt into markdown format.

Consider checking the 4th item in issue #143

### CODE REVIEW

**Comment by gutierri** [comment]
One suggestion to leave the README better would be to throw some things to the Wiki (from GitHub) and links to Wiki pages.
@jaap-karssenberg What do you think?

**Comment by ahangarha** [comment]
As a late reply, I would exhibit my agreement on your suggestion. Investing on wiki is great.

Yet I think my change in this particular PR would be helpful. Wish to know why it neither merged or rejected.

**Comment by Osndok** [comment]
> Wish to know why it neither merged or rejected.

Probably because Jaap has a life outside of zim :)

**Comment by jaap-karssenberg** [comment]
Merged as ce49ed412c922824cb4543957cbc7a01670b3574

Sorry for the long timeout. Had a whole pile of documentation updates that I wanted to merge at once. But indeed easier to just merge things as they come.

**Pull request closed without merging**
