### PR TITLE
Autocompletion / autocorrection plugin

### PR DESCRIPTION
**Pull request by Dav-d**
Hi,

I think it would be usefull to have an autocompletion plugin with the ability to modify a custom dictionary.

Thank you for your job.

### CODE REVIEW

**Comment by sojusnik** [comment]
I like how Gedit implemented wordcompletion. Easily installable in Ubuntu by `sudo apt install gedit-plugin-word-completion`.

Zim could pull those words from a general dictionary and also use words from the current note (or maybe from the last 10 used notes, as an example) to interactively autocomplete them, see Gedit's plugin for example.

BTW, Zim already has some type of autocompletion, in this case it's an autocorrection, realized through the "insert symbol" plugin, as mentioned [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/846).

**Comment by Dav-d** [comment]
I didn't know the Gedit wordcompletion. It's a very good model. But it doesn't work from a dictionary.
So I think too that Zim could work from a dictionary and from notes.

Thank you for the "insert symbol" plugin, (but it doesn't replace a realtime word autocompletion).

**Comment by Dav-d** [comment]
Here is a screeshot from gedit : 

zim-plugin-autocompletion

and a template to add new custom completions  (from LibreOffice) :
zim-plugin-autocompletion-dictionary
It could do too the job of the insert symbol plugin.

In Libreoffice there is too an usefull option : a checkbox to add or not a space after the inserted word.

**Comment by Dav-d** [comment]
Actually, I think there is a difference between autocompletion and autocorrection (self-correction ?).

Autocompletion means suggestions as gedit do from note or a word dictionary.

Autocorrection means to replace a word by another after pressing the space bar ie: "zw" --> "zim-wiki", from a replacement list like the sources.list.

I think that an autocorrection plugin will be easier to develop from the insert symbol plugin, isn't it ?

**Comment by Dav-d** [comment]
Here is an example from the file symbol.list to add the autocorrection ability :

```
## Suggestions for more shortcuts are welcome - please file in bug tracker ##
wd		word
wrd		word
templte	template
tpl		template
etc.
```

**Comment by jaap-karssenberg** [comment]
Something went wrong here - looks like you use a merge request for an unrelated issue / proposal. Please file as proper issue.

**Comment by introt** [comment]
Hi @Dav-d, have you tried https://github.com/introt/zim-plugin-text-replacer?

**Pull request closed without merging**
