### PR TITLE
New syntax (anchors) → bump WIKI_FORMAT_VERSION

### PR DESCRIPTION
**Pull request by Self-Perfection**
Release 0.74 introduced changes to syntax format that should be reflected in format version.

### CODE REVIEW

**Comment by jaap-karssenberg** [comment]
We discussed and chosen not to do so since a) this syntax was reserved
already for object usage and b) no upgrade available for edge cases where
there might be a conflict.

Op di 21 sep. 2021 12:04 schreef Alexander Meshcheryakov <
***@***.***>:

**Comment by Self-Perfection** [comment]
I don't quite understand this reasoning. What upgrade you might expect for conflicting cases? What is it, how should it behave?

Anyway if this have been discussed and decision have been made then feel free to reject this PR. I honestly assumed that this was forgotten.

I just want to highlight that new syntax does not handled nicely with older zim versions, namely 0.73.2. Link `Some:Note#Section' leads to page `Some:NoteSection`.

**Comment by jaap-karssenberg** [comment]
Yes, I understand the conflict. My reasoning is that a version bump only
helps if there is also code using the version to make the conflicts go
away. In this case there is no such compatibility.

**Comment by Self-Perfection** [comment]
Even if Zim does not have special code to handle this format change other tools and apps might have such special handling.

Or let me put it this way: seeing `Wiki-Format: zim 0.6` at the top of text file provided particular expectations before. And now one does not know what to expect exactly. Value '0.6' was deprived of its meaning.

**Pull request closed without merging**
