### PR TITLE
Convert large notebook script to python3

### PR DESCRIPTION
**Pull request by mexicarne**
Make zim-desktop-wiki/tools/create_large_test_notebook.py work with python 3

### CODE REVIEW

**Comment by jaap-karssenberg** [comment]
Thanks for the fix. Looks like the diff has some whitespace changes - is indenting consistent over the file using TAB ?

**Comment by mexicarne** [comment]
> Thanks for the fix. Looks like the diff has some whitespace changes - is indenting consistent over the file using TAB ?

No, the whole file was converted to space indenting per pep8 and because most lines in this file already was indented by space. Do you prefer to convert it tab instead?

**Comment by jaap-karssenberg** [comment]
Yes, please, zim code base ignores that part of pep8 :)

For the source code there is a test to enforce the indenting - probably I
should make it cover the tools section as well.

**Comment by mexicarne** [comment]
Done in 0b6223a

**Pull request merged**
